export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';


// Book Detail  Page

export const FETCH_BOOK_DETAIL_REQUEST = 'FETCH_BOOK_DETAIL_REQUEST';
export const FETCH_BOOK_DETAIL_SUCCESS = 'FETCH_BOOK_DETAIL_SUCCESS';
export const FETCH_BOOK_DETAIL_FAILURE = 'FETCH_BOOK_DETAIL_FAILURE';